import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import "@/app/globals.css";
import AOSInit from "@/component/AOSInit";
import Header from "@/component/Header";
import Footer from "@/component/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru" data-bs-theme="dark">
      <body className="bg-black">
        <AOSInit />
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
