import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import "@/app/globals.css";
import AOSInit from "@/component/AOSInit";
import Header from "@/component/Header";
import Footer from "@/component/Footer";
import Modal from "@/component/Modal";
import Nav from "@/component/Nav";
import Script from 'next/script';

export const metadata = {
  title: "4mobile - Все для вашего телефона",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const res = await fetch('https://api.4mobile.kz/api/content/items/categories', {
        method: 'GET',
        headers: {
            "api-key": "USR-22f5347f0fba81f53ecba0abf04ef430bf7bd40d"
        }
    });
    const navData = await res.json();
  return (
    <html lang="ru" data-bs-theme="dark">
      <body className="bg-black">
        <AOSInit />
        <Modal/>
        <Header />
        <Nav linkJson={navData} />
        {children}
        <Footer/>
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        />
      </body>
    </html>
  );
}
